credentials:
  usernames:
    doctor1:
      email: doctor1@example.com
      name: Doctor One
      password: 'abc123'  # Use hashed passwords for production

cookie:
  name: flowerclinic_cookie
  key: some_secret_key
  expiry_days: 1
